# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - name: npm run lint
      if: startsWith(matrix.node-version, 10) || startsWith(matrix.node-version, 12) || startsWith(matrix.node-version, 14)
      run: npm run lint

    - run: npm run type-check

    - run: npm run build

    - name: npm run test
      if: startsWith(matrix.node-version, 10) || startsWith(matrix.node-version, 12) || startsWith(matrix.node-version, 14)
      run: npm run test

    - name: push bundle
      if: startsWith(matrix.node-version, 10)
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Gustavo Ingrassia
        author_email: gustavo.ingrassia@gmail.com
        message: "build app"
        add: "lib"
        force: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
